version: "3.8"
services:
  db:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - 27017:27017

  backend:
    container_name: backend-cont
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - 5000:5000
    depends_on:
      - db

  frontend:
    container_name: frontend-cont
    build: ./frontend
    env_file:
      - ./frontend/.env.sample
    ports:
      - 5173:5173

  redis:
    container_name: redis
    image: redis:7.0.5-alpine 
    restart: unless-stopped
    expose: 
      - 6379
    depends_on:
      - db

volumes:
  data:
