apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: wanderlust
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sid716/wanderlust-frontend:v1.0.0
          ports:
            - containerPort: 5173
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: wanderlust
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - targetPort: 5173
      port: 5173
      nodePort: 31000
      protocol: TCP
